name: 'Check coverage for PR'

on:
  pull_request:

jobs:
  run-tests-check-coverage:
    name: Run tests & check coverage
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read # for private repos
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: 'Install pnpm'
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320

      - name: 'Install latest node version'
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Node packages
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run tests and prepare coverage report
        run: pnpm test:coverage

      - name: Vitest coverage report
        uses: davelosert/vitest-coverage-report-action@2500dafcee7dd64f85ab689c0b83798a8359770e
